### ISSUE TITLE
Cancel button not working

### ISSUE THREAD

**Issue by sammagafu** [sammagafu/weXchange#7]
On file screens>userdashboard>tabs

State managemnt feature is required, to store unmodified list of cancelled trips. Which will be checked when new stream of trips is detected

**Comment by xxGreyscale** [comment]
So it cancels all trips when a new trip is detected?

**Comment by sammagafu** [comment]
No only the current detected one.
So it adds the tripid to unmodified list, when the trip exists in cancelled trip the stream provider wont work

**Comment by xxGreyscale** [comment]
The cancel button will now change the state and listen for another trip request if available (Not likely).
